// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, age) VALUES (?, ?)
`

type CreateUserParams struct {
	Name string
	Age  int32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.Age)
	return err
}

const deleteUserByName = `-- name: DeleteUserByName :execresult
DELETE FROM users WHERE name = ?
`

func (q *Queries) DeleteUserByName(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUserByName, name)
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, name, age FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.Age); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserAge = `-- name: UpdateUserAge :execresult
UPDATE users SET age = ? WHERE name = ?
`

type UpdateUserAgeParams struct {
	Age  int32
	Name string
}

func (q *Queries) UpdateUserAge(ctx context.Context, arg UpdateUserAgeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserAge, arg.Age, arg.Name)
}
